// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars.Data;

#nullable disable

namespace StarWars.Migrations
{
    [DbContext(typeof(StarWarsContext))]
    [Migration("20240728113811_AddColumnsPeople")]
    partial class AddColumnsPeople
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StarWars.Models.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LaserSword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PlanetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Race")
                        .HasColumnType("int");

                    b.Property<string>("StarshipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlanetName");

                    b.HasIndex("StarshipName");

                    b.ToTable("People");
                });

            modelBuilder.Entity("StarWars.Models.Planet", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Climate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gravity")
                        .HasColumnType("int");

                    b.Property<int?>("PeopleId")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("PeopleId");

                    b.ToTable("Planet");
                });

            modelBuilder.Entity("StarWars.Models.Starship", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Gravity")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeopleId")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("PeopleId");

                    b.ToTable("Starship");
                });

            modelBuilder.Entity("StarWars.Models.People", b =>
                {
                    b.HasOne("StarWars.Models.Planet", "Planet")
                        .WithMany()
                        .HasForeignKey("PlanetName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWars.Models.Starship", "Starship")
                        .WithMany()
                        .HasForeignKey("StarshipName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");

                    b.Navigation("Starship");
                });

            modelBuilder.Entity("StarWars.Models.Planet", b =>
                {
                    b.HasOne("StarWars.Models.People", null)
                        .WithMany("planet")
                        .HasForeignKey("PeopleId");
                });

            modelBuilder.Entity("StarWars.Models.Starship", b =>
                {
                    b.HasOne("StarWars.Models.People", null)
                        .WithMany("starship")
                        .HasForeignKey("PeopleId");
                });

            modelBuilder.Entity("StarWars.Models.People", b =>
                {
                    b.Navigation("planet");

                    b.Navigation("starship");
                });
#pragma warning restore 612, 618
        }
    }
}
